### sHydrograph packages

library(shiny)
library(shinyjs)
library(markdown)
library(jsonlite)
library(tidyr)
library(plyr)
library(dplyr)
library(lmomco)
library(ggplot2)
library(ggridges)
library(scales)
library(date)
library(lubridate)
library(reshape2)
library(zoo)
library(dygraphs)
library(xts)
library(fs)
require(curl)


source("pkg/js.R", local = TRUE)
source("pkg/loc_info.R", local = TRUE)
source("pkg/xref.R", local = TRUE)
source("func/collect_interval.R", local = TRUE)
source("func/frequency_analysis.R", local = TRUE)
source("func/gam.R", local = TRUE)
source("func/YCDB_interval_clean.R", local = TRUE)
source("func/YCDB_API_query.R", local = TRUE)



# install.packages('shiny')
# install.packages('shinyjs')
# install.packages('markdown')
# install.packages('jsonlite')
# install.packages('tidyr')
# install.packages('plyr')
# install.packages('dplyr')
# install.packages('lmomco')
# install.packages('ggplot2')
# install.packages('scales')
# install.packages('date')
# install.packages('lubridate')
# install.packages('reshape2')
# install.packages('zoo')
# install.packages('dygraphs')
# install.packages('xts')
# install.packages('fs')

# install.packages('rlang')
